blank_issues_enabled: true
contact_links:
  - name: "Main PrivSec.dev Repository"
    url: "https://github.com/PrivSec-dev/privsec.dev"
    about: "​"
  - name: "PrivSec.dev Matrix Chat"
    url: "https://matrix.to/#/!GDRXkRlmSfDOhfEWGE:arcticfoxes.net?via=arcticfoxes.net&via=matrix.org&via=grapheneos.org"
    about: "General questions and discussions. #privsec:arcticfoxes.net"
